### ISSUE TITLE
remove old repository to prevent confusion

### ISSUE THREAD

**Issue by alanhamlett** [CodeCavePro/monodevelop-wakatime#10]
The [old repo location](https://github.com/salaros/monodevelop-wakatime) should be deleted since this is the new location going forward.

**Comment by alanhamlett** [comment]
It looks like the old repo is the one being developed on? We should delete this repo then?

**Comment by salaros** [comment]
Nope. There was a PR (I didn't notice it was on the old repo) I accepted it while traveling, but later I realized it was on the wrong repo, it removed Windows support completely and messed few more things.
Anyway I've just removed the old repo
