### ISSUE TITLE
The type initializer for 'WakaTime.WakaTimeConfigFile' threw an exception.

### ISSUE THREAD

**Issue by diogokobbi** [CodeCavePro/monodevelop-wakatime#13]
Hi, my monodevelop version is 7.5 (build 1255) and Mono runtime is: Mono 5.10.1.47 (tarball Tue Apr 17 15:12:35 UTC 2018) (64-bit).

When i try to set the API Key on Wakatime settings, monodevelop displays a popup with the message: The type initializer for 'WakaTime.WakaTimeConfigFile' threw an exception.

**Comment by diogokobbi** [comment]
![image](https://user-images.githubusercontent.com/7206693/42610506-4f08865e-8568-11e8-8d5a-721baefec009.png)

**Comment by salaros** [comment]
Hi @diogokobbi 

Thanks for reporting the issue. Sorry if it took so long, but I was on a long vacation 😄🌴
please test v3.0.4 it locally and let me know if the addin works fine for you too

**Comment by diogokobbi** [comment]
All fine. Thank you!
