### ISSUE TITLE
WakaTime ignoring key in .wakatime.cfg

### ISSUE THREAD

**Issue by shederman** [CodeCavePro/monodevelop-wakatime#14]
I'm running VisualStudio 2017 on a Mac (So, Xamarin under the hood). Using the WakaTime extension. When VS starts it asks for the API key, even though I've entered it several times, and it's in the .wakatime.cfg file. I've done chmod 755 on all .wakatime files in case it's a permissions issue, but no joy.

Any ideas?

**Comment by salaros** [comment]
Ooops. My bad I've accidentally committed a row I added for testing purposes. Please update the add in and let me know if it works for you.
There is only one known bug left (which occurs from  time to time) with proxy value not being saved correctly, but I will address it tomorrow

**Comment by salaros** [comment]
@shederman please let me know if it worked for you. Fill free to star the repo if you want to support me 😄

**Comment by shederman** [comment]
Perfect, works 100%. Thanks for the amazingly quick response!
