### ISSUE TITLE
Update for Visual Studio for Mac 2019

### ISSUE THREAD

**Issue by vnwonah** [CodeCavePro/monodevelop-wakatime#15]
This no longer works in Visual Studio for Mac 2019

**Comment by salaros** [comment]
Indeed, being macOS not my primary platform I haven't ported the addin to VS for Mac 2019 yet.
Certainly I'm going to address it very soon (most likely on within next few days)

**Comment by vnwonah** [comment]
I am interested in helping out if you don’t mind. If you can tell me what to do I will find how to do it.

**Comment by KShaibani** [comment]
Hi, Any updates regards this issue?

**Comment by sashok2k** [comment]
Hi, I also would like to have this extension for VS 2019 for Mac

**Comment by KShaibani** [comment]
Hi all, I manage to build it myself last week and release the add-in in my repo today and it's working as expected, (https://github.com/KShaibani/monodevelop-wakatime) because I don't know if I do it the right way or not (the way I ported the add-in to support Visual Studio for Mac 2019)

_side note: in WakaTime the editor name is MonoDevelop not Visual Studio for Mac, I don't know how to change the ide name._ @alanhamlett can you help, thanks

step by step :
```
1.clone rep
2.before open in the .csproj project file, open visual studio for mac and install or enable these extensions ( MSBuild editor / AddinMaker )
3.open the .csproj project file 
4. update all NuGet Packages
5. install this NuGet Package ( MonoDevelop.Addins 0.4.7)
6. open and edit the .csproj project file.
    - line 60 (.\packages\MonoDevelop.Addins.0.4.7\build\MonoDevelop.Addins.targets).
    from: 
      <Import Project="..\packages\MonoDevelop.Addins.0.2.3\build\net40\MonoDevelop.Addins.targets" Condition="Exists('..\packages\MonoDevelop.Addins.0.2.3\build\net40\MonoDevelop.Addins.targets')" />
      to:
        <Import Project=".\packages\MonoDevelop.Addins.0.4.7\build\MonoDevelop.Addins.targets" Condition="Exists('.\packages\MonoDevelop.Addins.0.4.7\build\MonoDevelop.Addins.targets')" />
    - line 138 
    to :
        <Exec Command="'/Applications/Visual Studio.app/Contents/MacOS/vstool' setup pack $(OutputAbsolutePath)MonoDevelop.WakaTime.addin.xml" ContinueOnError="true" WorkingDirectory="$(OutputAbsolutePath)" />   

7. open MonoDevelop.WakaTime.addin.xml change Dependencies to this version
    <Dependencies>
        <Addin id="Ide" version="8.0" />
        <Addin id="Core" version="8.0" />
    </Dependencies>

8. update targets framework to .NET framework 4.7.2
    - project Option > build > General > Target framework > .NET framework 4.7.2

9. run & build (for testing)

10. install the add-in manually.
    - go to extensions > instal form file > go to (project path) : ⁨monodevelop-wakatime⁩/bin⁩/⁨Debug⁩/
    - click in MonoDevelop.WakaTime_X.X.X.mpack and instal.

11. (Optionally) in Terminal cd to (⁨Path to the project folders)
    - cd ⁨monodevelop-wakatime⁩/bin⁩/⁨Debug⁩/
    - /Applications/Visual\ Studio.app/Contents/MacOS/vstool setup pack MonoDevelop.WakaTime.dll

```
thanks

@salaros @sashok2k @vnwonah

**Comment by salaros** [comment]
Hey, thanks. I know how to adapt it, I've already done it for several versions and platforms, unfortunately I cannot upload the compiled addin to the gallery...... because the login page doesn't work.

![image](https://user-images.githubusercontent.com/675348/58732704-f9f29c80-83fa-11e9-88a5-0516e4d5d8c8.png)

![image](https://user-images.githubusercontent.com/675348/58732729-0aa31280-83fb-11e9-878c-965e010afc14.png)

**Comment by KShaibani** [comment]
thanks @salaros for your explanation.. what if we go using the manual install approach as a temporary solution until the page login issue resolved

**Comment by salaros** [comment]
@KShaibani I don't have access to my mac mini right now, so I only have Linux and Windows
However I've pushed some changes to the master branch and uploaded a [new addin version to releases page](https://github.com/CodeCavePro/monodevelop-wakatime/releases/tag/4.0.1)

Please try it and let me know

**Comment by KShaibani** [comment]
@salaros I install the addin (4.0.1) in Visual Studio for Mac 2019, and it's working and I see the update in wakatime side.

**Comment by salaros** [comment]
@KShaibani nice. I'm glad it works. I've wrote to guys supporting MonoDevelop adding gallery again. I hope they will fix the login page ASAP

**Comment by KShaibani** [comment]
Thanks @salaros 👌🏼👍🏼

**Comment by salaros** [comment]
@sashok2k @KShaibani @vnwonah @ermshiperete 
guys could you please try to download the addin from the gallery (for those who already installed it manually: you have to remove it first, restart VS for Mac and then try to install it from addin gallery)

**Comment by KShaibani** [comment]
hi @salaros , I remove the manually installed addin (wakatime), and after restarting VS For mac. I can't find the addin in the gallery. I try to add this repo URL in the Extension Repository Management.
(https://addins.monodevelop.com/Stable/Mac/8.0/main.mrep)
after I added URL the addin show up in the gallery. 
the addin it's only available in the repo(8.0). not 8.0.9 (https://addins.monodevelop.com/Stable/Mac/8.0.9/main.mrep)
I hope this helps.

**Comment by salaros** [comment]
Hm.... that's really strange. In the past (ver 5.x, 6.x, 7.x I had to upload the addin only for major releases, so later it was included in .mrep files of point releases automatically)
Seems like other devs are still doing it the old way:

![image](https://user-images.githubusercontent.com/675348/59156104-6a09be00-8a9e-11e9-9ca9-05c66e8605fb.png)

but apparently Microsoft has ruined this very convenient functionality for 8.x versions,
I'm not even surprised 😄 

I will publish addin for all point releases, yay!

**Comment by adamsoutar** [comment]
I'm not sure if it's related to VS for Mac 2019, so I didn't know whether to open a new issue, but I didn't get anything asking for my API key when installing plugin v4.0.1 on VS Mac 8.1.1?

Is there a plugin settings page or somewhere to enter the key or is it supposed to prompt you?

**Comment by salaros** [comment]
@Adybo123 hi, there is a settings page. Probably you were using WakaTime in some other IDE and since all IDEs share settings via .wakatime.cfg file you have API key already filled out.
