### ISSUE TITLE
Sending duplicate heartbeats

### ISSUE THREAD

**Issue by alanhamlett** [CodeCavePro/monodevelop-wakatime#16]
The Monodevelop plugin is sending duplicate heartbeats with the same time, entity, project, etc. Possibly related to #8.

**Comment by alanhamlett** [comment]
Further investigation looks like the extension is sending heartbeats without user interaction, maybe from automated build or compile events. This generates hundreds to thousands of heartbeats all with `time` attribute within the same second. These heartbeats are generated for files not normally edited or opened, for ex:

* `Artifacts/Legacy/08/08b5342f8fa194d31b75295468a24e4c.info`
* `Assets/02.Scripts/App/Node.cs.meta`
* `Temp/UnityTempFile-7c08957751d404cc9817bd8d117c5407`

**Comment by HobDev** [comment]
I got this mail from support@wakatime.com:

> We noticed some unusual coding activity from your Monodevelop WakaTime plugin Yesterday:
> You have many duplicate heartbeat events.
> 
> In rare cases, other Monodevelop extensions can cause problems with WakaTime. Please make sure your other Monodevelop extensions are not simulating cursor movements or saving files in the background. This can trick the WakaTime plugin into thinking you were typing even when you weren’t using your Monodevelop editor.
> 

Is the e-mail related to this issue. Please note I usually kept open multiple instance of Visual Studio for mac 2019.

**Comment by alanhamlett** [comment]
> Is the e-mail related to this issue.

Yes, that email is triggered whenever we detect plugins with bugs. We're waiting for @salaros to merge #17 to fix the bug. Until then, that automated email might be sent.

**Comment by alanhamlett** [comment]
Thanks!

**Comment by salaros** [comment]
@alanhamlett thank you for your contribution, sorry if it took so long to merge it.
BTW I republished addin for different VS for Mac versions, @alanhamlett @HobDev please test it with your current version (8.3 preview versions are supported too, I haven't tried them yet, so having a feedback would be great).
