### ISSUE TITLE
have to remove wakatime-master folder to start logging

### ISSUE THREAD

**Issue by salaros** [CodeCavePro/monodevelop-wakatime#4]
_From @s1m0n1stv4n on January 27, 2016 8:16_

Using monodevelop-unity 5.9.6 in osx, loggin simply doesn't start. Oddly if I remove the generated wakatime-master folder from the home folder and restart monodevelop, logging works as expected for this session. So I have to remove the folder every time before restarting monodevelop for wakatime to work. Any suggestions?

_Copied from original issue: salaros/monodevelop-wakatime#5_

**Comment by salaros** [comment]
Hi, are you using the lastest version available from extension repository (extension version should be 1.0.3)? Anyway tomorrow I will get access to my Mac and will try to dig into this problem.

**Comment by salaros** [comment]
_From @s1m0n1stv4n on January 28, 2016 11:41_

Yes, the latest. Thanks for looking into it!

**Comment by salaros** [comment]
Hi, I've just tested the latest version of WakaTime extension v1.0.5 on my Mac OS X 10.11 with Xamarin Studio 5.10 and everything seem to work smoothly, among other things it includes a bugfix from [ermshiperete](https://github.com/CodeCavePro/wakatime-sharp/commit/b5860422dd0e1566282fc06d1027d526fb86b272) which probably addresses your issue (addin kept downloading WakaTime CLI on IDE startup).

For instance I've also tried to restart IDE few times (forcibly quitting each time), in each session I was editing new files so later I just had to check if all of them are listed on my WakaTime dashboard.

Please update your addin and try to reproduce the issue and report your results here so we can close the issue or investigate further.

**Comment by ghost** [comment]
Works great with 1.0.5! Everything seems fine. Thank you!

**Comment by salaros** [comment]
Good to hear that! You welcome.
